# -*- coding: utf-8 -*-
"""Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkrtD5a7b9TakqALU4mGlAYBqllPGw0Q
"""

from transformers import pipeline
sentiment_analyzer = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)
print("Sentiment Analysis model loaded successfully!")

texts = ["I love this product!It's amazing.",
         "The service was terrible and I'm very disappointed.",
         "It's okay, not great but not bad either."]

for text in texts:
  result = sentiment_analyzer(text)
  print(f"Text: {text}")
  print(f"Sentiment: {result[0]['label']}")
  print(f"Confidence: {result[0]['score']:.2f}")
  print()

custom_text = input("Enter a sentence for sentiment analysis: ")
result = sentiment_analyzer(custom_text)
print(f"\nSentiment: {result[0]['label']}")
print(f"Confidence: {result[0]['score']:.2f}")

long_text = """
The product is good overall, but there are some issues with battery life.
I wish it lasted longer. However, the design is sleek, and I am happy with the performance so far.
"""
result = sentiment_analyzer(long_text)
for res in result:
  print(f"Sentiment: {res['label']}, Confidence: {res['score']:.2f}")

